apiVersion: v1
kind: Service
metadata:
  name: node-api-service
  namespace: default
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "4000"
    prometheus.io/path: "/metrics"
  labels:
    app: node-api
spec:
  type: LoadBalancer
  selector:
    app: node-api
  ports:
    - name: web
      protocol: TCP
      port: 4000
      targetPort: 4000